---
name: Build Synapse Stack

on:
  workflow_call:
    inputs:
      STACK:
        required: true
        type: string
        description: staging or prod
      INSTANCE:
        required: true
        type: string
        description: example, 544
      REPO_AND_WORKERS_VERSION:
        required: true
        type: string
      REPO_BEANSTALK_VERSION:
        required: true
        type: number
        description: example, 0
      PORTAL_VERSION:
        required: true
        type: string
        description: example, 544.0-4-gd18c3167f2
      PORTAL_BEANSTALK_VERSION:
        required: true
        type: number
        description: example, 0
      VPC_SUBNET_COLOR:
        required: true
        type: string
        description: Red, Green, or Blue


env:
   RUNNER_LABEL: deployment-runner
   PATH_TO_SCRIPT: scripts
   PATH_TO_SOURCE_CODE: src

jobs:
  # this is necessary to make env values available to later jobs
  get-env:
    runs-on: ubuntu-latest
    steps:
       - run: echo "null"
    outputs:
      RUNNER_LABEL: ${{ env.RUNNER_LABEL }}
      PATH_TO_SCRIPT: ${{ env.PATH_TO_SCRIPT }}
      PATH_TO_SOURCE_CODE: ${{ env.PATH_TO_SOURCE_CODE }}

  ensure-runner-exists:
    needs: get-env
    uses: "./.github/workflows/ensure_runner_exists.yml"
    with:
      LABEL: ${{ needs.get-env.outputs.RUNNER_LABEL }}
      CONTEXT: ${{ vars.CONTEXT }}
      ROLE_TO_ASSUME: ${{ vars.ROLE_TO_ASSUME }}
      SYNAPSE_DEPLOYMENT_ROLE: ${{ vars.SYNAPSE_DEPLOYMENT_ROLE }}
    secrets: inherit

  execute-script:
    runs-on: ${{ needs.get-env.outputs.RUNNER_LABEL }}
    needs: [ensure-runner-exists, get-env]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: Sage-Bionetworks/synapse-ops-core
          ref: main
          path: ${{ needs.get-env.outputs.PATH_TO_SCRIPT }}

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: Sage-Bionetworks/Synapse-Stack-Builder
          ref: develop
          path: ${{ needs.get-env.outputs.PATH_TO_SOURCE_CODE }}

      - name: Execute script
        run: >
          ${{ needs.get-env.outputs.PATH_TO_SCRIPT }}/scripts/build_synapse_stack.sh
          ${{ inputs.STACK }}
          ${{ inputs.INSTANCE }}
          ${{ inputs.REPO_AND_WORKERS_VERSION }}
          ${{ inputs.REPO_BEANSTALK_VERSION }}
          ${{ inputs.PORTAL_VERSION }}
          ${{ inputs.PORTAL_BEANSTALK_VERSION }}
          ${{ inputs.VPC_SUBNET_COLOR }}
          ${{ needs.get-env.outputs.PATH_TO_SOURCE_CODE }}
...
